#### 1. Импортируйте пакет numpy под именем `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Создайте нулевой вектор размера 10 (★☆☆)

In [ ]:
a = np.zeros(10)

#### 3. Как узнать объем памяти любого массива (★☆☆)

In [ ]:
a.nbytes

80

#### 4. Создайте вектор со значениями от 10 до 49. (★☆☆)

In [ ]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Создайте обратный вектор из вектора в задании 4 (первый элемент становится последним) (★☆☆)

In [ ]:
b = b[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6. Создайте матрицу 3x3 со значениями от 0 до 8. (★☆☆)

In [ ]:
b = np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Найти индексы ненулевых элементов из [1,2,0,0,4,0 (★☆☆)

In [ ]:
a = [1,2,0,0,4,0]
b = np.nonzero(a)
print(b)

(array([0, 1, 4]),)


#### 8. Создайте массив 3x3x3 со случайными значениями (★☆☆)

In [ ]:
b = np.random.random((3,3,3))
print(b)

[[[0.66026599 0.1674791  0.72491867]
  [0.25687126 0.14994502 0.30369297]
  [0.62547345 0.5898993  0.1522832 ]]

 [[0.65700971 0.07757702 0.60255658]
  [0.49715935 0.57079498 0.40372843]
  [0.35014577 0.54546098 0.96663811]]

 [[0.92466666 0.50947976 0.6497368 ]
  [0.222941   0.4422969  0.43727704]
  [0.60215561 0.80053254 0.60732613]]]


#### 9. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения. (★☆☆)

In [ ]:
b = np.random.random((10,10))
min = b.min()
max = b.max()
print(b)
print(min, max)

[[0.78657514 0.86861688 0.54831229 0.2680391  0.888515   0.4221362
  0.04182415 0.12015338 0.41413099 0.29254756]
 [0.5751089  0.66850503 0.91215561 0.71271373 0.82038864 0.90418504
  0.59846537 0.36422142 0.61847442 0.6182015 ]
 [0.19875939 0.85474697 0.00748362 0.67511556 0.48895741 0.38654121
  0.91223927 0.67795862 0.43776239 0.28469845]
 [0.25921696 0.8853308  0.45481284 0.13856173 0.59111818 0.39972161
  0.18557185 0.9928766  0.16078668 0.87241761]
 [0.08771777 0.05845996 0.1705434  0.76227168 0.31446318 0.78013205
  0.33100488 0.71394104 0.15110914 0.6899737 ]
 [0.62115083 0.83114659 0.53859339 0.23097987 0.6928943  0.14087074
  0.77852548 0.28521181 0.82475393 0.27575112]
 [0.10025057 0.28724085 0.62374103 0.63115747 0.42643751 0.6485797
  0.85375585 0.31574878 0.07680638 0.4961811 ]
 [0.20142436 0.00303783 0.72226675 0.51352172 0.03805967 0.91264462
  0.53109036 0.8540463  0.2695469  0.22447156]
 [0.97409971 0.03715428 0.00728679 0.66196455 0.81132488 0.70980998
  0.61063701 0

#### 10. Создайте случайный вектор размера 30 и найдите среднее значение(★☆☆)

In [ ]:
b = np.random.random((10,10))
m = b.mean()
print(m)

0.520140927882862


#### 11. Создайте массив 2d 2x3 c 1 на границе и 0 внутри (★☆☆)

In [ ]:
x = np.ones((10, 10))
x[2:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 12. Каков результат следующего выражения? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 13. Рассмотрим массив размера (6,7,8). Каков индекс (x,y,z) 100-го элемента? (★☆☆)

In [ ]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 14. Умножить матрицу 5x3 на матрицу 3x2(★☆☆)

In [ ]:
w = np.dot(np.ones((5,3)), np.ones((3,2)))
print(w)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 15. Создайте одномерный массив со случайными значениями от 1 до 10, инвертируйте (поменяйте местами) все элементы, со значениями 3 и 8. (★☆☆)

In [ ]:
b = np.random.randint(0, 10, (12))
#b = np.array([1, 3, 3, 3, 8, 8])
print(b)
for i in range(len(b)):
  if b[i] == 3:
    b[i] = 8
  elif b[i] == 8:
    b[i] = 3
print(b)

[5 1 5 6 9 5 5 1 6 3 5 4]
[5 1 5 6 9 5 5 1 6 8 5 4]


#### 16. Каков результат следующих выражений? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-16-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-16-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 17. Как найти общие значения между двумя массивами? (★☆☆)

In [ ]:
a = np.array([2, 4, 7, 1, 4])
b = np.array([7, 2, 9, 0, 5])
c = np.intersect1d(a, b)
print(c)

[2 7]


#### 18. Как вычислить ((A+B)*(-A/2)) с заменой массива А (без копирования)? (★★☆)

In [ ]:
A = np.ones(3)*1
print(A)
B = np.ones(3)*2
print(B)

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
print(np.multiply(A,B,out=A))


[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]


#### 19. Создайте матрицу 5x5 со значениями строк от 0 до 4. (★★☆)

In [ ]:
b = np.zeros((5,5))
b += np.arange(5)
print(b)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 20. Создайте вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0 (★★☆)

In [ ]:
b = np.linspace(0,1,12)[1:-1]
b

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 21. Создайте случайный вектор размера 10 и отсортируйте его (★★☆)

In [ ]:
b = np.random.random(10) 
b
b.sort()
b

[0.30209395 0.26452968 0.41957618 0.27091775 0.36772786 0.91480674
 0.52420507 0.20017762 0.19823002 0.05359443]
[0.05359443 0.19823002 0.20017762 0.26452968 0.27091775 0.30209395
 0.36772786 0.41957618 0.52420507 0.91480674]


#### 22. Можно ли суммировать небольшой массив быстрее, чем np.sum? (★★☆)

In [ ]:
import timeit

x = [1, 2, 3]

def Psum():
    return sum(x)

def numpy_sum():
    return np.sum(x)

n = 1000

t1 = timeit.timeit(Psum, number = n)
print(t1)
t2 = timeit.timeit(numpy_sum, number = n)
print(t2)

0.0004114080000050535
0.03107573399999808


#### 23. Рассмотрим два случайных массива A и B, проверьте, равны ли они(★★☆)

In [ ]:
a = np.random.random((5)) 
b = np.random.random((5)) 
res = np.allclose(a,b)
print(res)

False


#### 24. Создайте случайный вектор размера 10 и замените максимальное значение на 0 (★★☆)

In [ ]:
b = np.random.random(10)
print(b)
b[b.argmax()] = 0
print(b)

[0.44118833 0.91137383 0.67231699 0.47984679 0.79548843 0.54693184
 0.78679156 0.35154707 0.44113737 0.61749562]
[0.44118833 0.         0.67231699 0.47984679 0.79548843 0.54693184
 0.78679156 0.35154707 0.44113737 0.61749562]


#### 25. Распечатайте минимальное и максимальное представимое значение для каждого скалярного типа numpy (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 26. Как вывести все значения большого массива? (★★☆)

In [ ]:
np.set_printoptions(threshold=np.inf)
print(np.arange(2001))

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#### 27. Рассмотрим случайный вектор формы (100,2), представляющий координаты, найдите расстояния между точками. (★★☆)

In [ ]:
c = np.random.random((100,2))
x,y = np.atleast_2d(c[:,0], c[:,1])
f = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(f)

[[0.         0.3762437  0.11578792 0.64735793 0.67761936 0.2474805
  0.60727004 0.49183761 0.33867839 0.08216306 0.50588741 0.80804379
  0.54301704 0.87561571 0.23755257 0.29816805 0.49921022 0.71616017
  0.89638435 0.34694709 0.28943217 0.18887148 0.29926007 0.24567766
  0.9377606  0.51718735 0.90606426 0.28836204 0.70034815 0.39705043
  0.8177124  0.58394995 0.43211744 0.30605491 0.73657217 0.57069791
  0.7726755  0.39578869 0.20489228 0.23797848 0.57641206 0.98895556
  0.48845248 0.501578   0.20620797 0.35662373 0.53612876 0.54181295
  0.78212766 0.42970749 0.74083051 0.05522791 0.59868269 0.61352793
  0.16876478 0.72403553 0.28051789 0.52043257 0.36824005 0.37728649
  0.40394495 0.48001521 0.49464667 0.76024278 0.38217027 0.53297067
  0.23345462 0.16804601 0.66501798 0.84034128 0.29011489 0.34594407
  0.61338887 0.28533675 0.14241299 0.18745152 0.38119062 0.40627593
  0.82069931 0.64386372 0.26045793 0.62369231 0.42145269 0.18976145
  0.42203614 0.28877962 0.78632545 0.36533374 0.5

#### 28. Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) с заменой?

In [ ]:
a = np.array([10.1, 20.2, 30.3, 40.4, 50.5])
a = a.astype('float32')
print(a.dtype)
a = a.astype('int32')
print(a)
print(a.dtype)

float32
[10 20 30 40 50]
int32


#### 29. Создайте массив из следующего файла: (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
import io
f = io.StringIO('''
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
 ''')
a = np.genfromtxt(f, delimiter = ",")
print(a)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 30. Вычтите среднее значение каждой строки случайной матрицы. (★★☆)

In [ ]:
a = np.random.rand(3, 4)
print(a)
print(a.mean(axis=1, keepdims=True))
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[0.76732249 0.175913   0.08381555 0.20286153]
 [0.72492497 0.45072955 0.1098021  0.26777822]
 [0.86465605 0.07221328 0.86342382 0.92916034]]
[[0.30747814]
 [0.38830871]
 [0.68236337]]
[[ 0.45984435 -0.13156514 -0.22366259 -0.10461661]
 [ 0.33661626  0.06242084 -0.27850661 -0.12053049]
 [ 0.18229267 -0.61015009  0.18106045  0.24679697]]


#### 31. Рассмотрим случайный вектор, как добавить 1 к каждому элементу, индексированному вторым вектором (будьте осторожны с повторяющимися индексами)? (★★★)

In [ ]:
a = np.ones(10)
N = 10
print(a)
I = np.random.randint(1,N-1,N)
print(I)
a += np.bincount(I, minlength=len(a))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 5 7 3 8 5 3 5 3 5]
[1. 2. 1. 4. 1. 5. 1. 2. 2. 1.]


#### 32. Как перенести элементы вектора (X) в массив (F) на основе списка индексов (I)? (★★★)

In [ ]:
X = [9, 8, 7, 23, 5, 6]
I = [1, 0, 2, 3, 5, 4]
F = np.bincount(I, X)
print(F)

[ 8.  9.  7. 23.  6.  5.]


#### 33. Рассматривая четырехмерный массив, как получить сумму сразу (в одну операцию) по двум последним осям? (★★★)

In [ ]:
def print_4dim_array(d_A: np.array):
    def my_replace(d_str:str):
        return d_str.replace('\n', '')
    print(*[' '.join(map(my_replace,map(str,e))) for e in d_A], sep='\n')
size_arr = (3,4,3,4)
Z = np.random.randint(0,2,size=size_arr)  

print('Исходный четырехмерный вектор')
print_4dim_array(Z)

sum = Z.sum(axis=(-2,-1))
print('Результат суммирования ', sum)

Исходный четырехмерный вектор
[[0 0 1 1] [1 1 0 1] [0 1 0 0]] [[1 1 0 0] [1 1 1 1] [0 0 0 0]] [[0 0 0 1] [0 0 1 0] [0 0 1 0]] [[0 1 1 0] [0 1 0 0] [0 0 1 0]]
[[0 1 0 0] [0 1 1 1] [0 1 0 0]] [[0 0 1 0] [0 0 0 0] [0 0 1 0]] [[1 1 0 1] [0 1 1 1] [0 1 0 1]] [[1 1 0 0] [0 1 0 0] [1 0 0 0]]
[[0 1 0 0] [0 0 1 1] [0 1 1 0]] [[1 0 1 1] [1 1 1 0] [1 0 1 1]] [[0 1 0 0] [0 1 1 0] [1 1 1 0]] [[0 1 0 0] [1 1 0 1] [1 0 0 1]]
Результат суммирования  [[6 6 3 4]
 [5 2 8 4]
 [5 9 6 6]]


#### 34. Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением? (★★★)

In [ ]:
a = np.array([1,2,3,4,5])
z = 3
a0 = np.zeros(len(a) + (len(a)-1)*(z))
a0[::z+1] = a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 35. Рассмотрим массив размерности (5,5,3), как его умножить на массив размерностью (5,5)? (★★★)

In [ ]:
a = 4*np.ones((5,5,3))
b = 5*np.ones((5,5))
c = a * b[:,:,None]
print(c)

[[[20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]]

 [[20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]]

 [[20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]]

 [[20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]]

 [[20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]
  [20. 20. 20.]]]


#### 36. Как вычислить средние значения, используя скользящее окно по массиву? (★★★)

In [ ]:
def moving_average(arr, d_size_window:int):
    '''
    функция которая возвращает средние значения скользящего окна по одномерному вектору
    arr - входящий массив
    d_size_window - размер окна
    '''
    if d_size_window>=1:
        cumsum_arr = np.cumsum(arr)
        cumsum_arr[d_size_window:] = cumsum_arr[d_size_window:] - cumsum_arr[:-d_size_window]
        return cumsum_arr[d_size_window - 1:] / d_size_window
    else:
        return arr
    
Z = np.arange(20)
print(f'Исходный вектор Z длинной {len(Z)}:\n', Z, '\n')
size_window = 2
moving_average_ww_2 = moving_average(Z, d_size_window=size_window)
print(f'Вектор средних значений скользящего окна рамера {size_window} вектора Z:\n', moving_average_ww_2)
print(f', длина вектора ', len(moving_average_ww_2), '\n')

size_window = 3
moving_average_ww_3 = moving_average(Z, d_size_window=size_window)
print(f'Вектор средних значений скользящего окна рамера {size_window} вектора Z:\n', moving_average_ww_3)
print(f', длина вектора ', len(moving_average_ww_3), '\n')

Исходный вектор Z длинной 20:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

Вектор средних значений скользящего окна рамера 2 вектора Z:
 [ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5
 14.5 15.5 16.5 17.5 18.5]
, длина вектора  19 

Вектор средних значений скользящего окна рамера 3 вектора Z:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
, длина вектора  18 



#### 37. Рассмотрим одномерный массив Z, постройте из него двумерный массив, первая строка которого (Z[0],Z[1],Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть (Z[ -3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 38. Рассмотрим 2 набора точек P0,P1, описывающих линии (2d), и набор точек P. Как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])?(★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[7.45289893 7.7437107  0.90429645 9.72778976 4.21419752 1.83169562
 3.15337907 3.86105541 5.01675233 4.62878027]


#### 39. Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
from numpy.lib import stride_tricks
N = 15  # размер массива
Z = np.arange(N,dtype=np.int32)
print(f'Исходный массив Z размера {Z.shape[0]}:\n', Z)

def rolling_window(d_array, d_size_window):
    shape = d_array.shape[:-1] + (d_array.shape[-1] - d_size_window + 1, d_size_window)
    strides = d_array.strides + (d_array.strides[-1],)
    return stride_tricks.as_strided(d_array, shape=shape, strides=strides)

size_window = 4
R = rolling_window(Z,size_window)
print(f'Искомый массив R размера {R.shape[0]} на {R.shape[1]} :\n', R)



Исходный массив Z размера 15:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Искомый массив R размера 12 на 4 :
 [[ 0  1  2  3]
 [ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 40. Найдите ранг случайной матрицы (★★★)

In [ ]:
from numpy.linalg import matrix_rank

r = matrix_rank(np.eye(4)) # диагональная матрица

print(np.eye(4))
print(r)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
4


#### 41. Как найти наиболее часто встречающееся значение в массиве?

In [ ]:
a = np.array([1, 4, 2, 3, 4, 5])
c = np.bincount(a)
print(np.argmax(c))

4


#### 42. Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B? (★★★)

In [ ]:
A = np.random.randint(1, 7, (8, 3))
B = np.random.randint(1, 7, (2, 2))
print(f'Массив а:\n{A}')
print(f'Массив b:\n{B}')
C = (A[..., np.newaxis, np.newaxis] == B)

I = np.where(C.any((3, 1)).all(1))[0]
print(f'Индексы искомых строк:\n{I}')

Массив а:
[[2 4 6]
 [2 3 3]
 [5 2 3]
 [1 3 3]
 [3 2 1]
 [4 5 2]
 [4 5 3]
 [4 3 1]]
Массив b:
[[5 6]
 [2 4]]
Индексы искомых строк:
[0 2 5 6]


#### 43. Как извлечь уникальные значения из 2-х двумерных массивов?(★★★)

In [ ]:
a = np.array([[1, 1, 2, 3, 4, 5],[1, 1, 2, 3, 4, 7]])
b = np.array([[88, 1, 8, 3, 4, 5],[1, 1, 95, 36, 14, 7]])
c = np.concatenate((a, b))
print(c)
print(np.unique(c))

[[ 1  1  2  3  4  5]
 [ 1  1  2  3  4  7]
 [88  1  8  3  4  5]
 [ 1  1 95 36 14  7]]
[ 1  2  3  4  5  7  8 14 36 88 95]
